apiVersion: apps/v1
kind: Deployment
metadata:
  name: java_deployment
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp 
    spec:
      containers:
      - name: javacont
        image: dixit7/hotstar:v3
        ports:
        - containerPort: 8080