apiVersion: v1
kind: Pod
metadata:
  name: mongodbpod
  labels:
    app: mongodbapp
  namespace: test
spec:
  containers:
  - name: mongodbcontainer
    image: mongo
    ports:
    - containerPort: 27017
    env:
    - name: MONGODB_ADMIN_USER_NAME
      value: "admin"
    - name: MONGODB_ADMIN_PASSWORD
      value: "admin123"