apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-keyvault-secrets
  namespace: test
spec:
  provider: azure

  secretObjects:
    - secretName: mysql-secret
      type: Opaque
      data:
        - objectName: mysql-root-username   # name of the Key Vault secret
          key: mysql-root-username          # key to store in Kubernetes secret
        - objectName: mysql-root-password
          key: mysql-root-password

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    useWorkloadIdentity: "true"
    clientID: "f0fbf836-557a-4295-ba6f-3cc861b30363"

    keyvaultName: "kv-zohobackend-backend"
    tenantId: "60d07259-90f0-4488-94de-59a66077488d"

    objects: |
      array:
        - |
          objectName: mysql-root-username
          objectType: secret              # secret | key | cert
          objectVersion: ""              # optional, latest if empty

        - |
          objectName: mysql-root-password
          objectType: secret
          objectVersion: ""
--- 

apiVersion: v1
kind: ServiceAccount
metadata:
  name: zoho-service-account
  namespace: test
  annotations:
    azure.workload.identity/client-id: f0fbf836-557a-4295-ba6f-3cc861b30363
